services:
  - type: web
    name: imae-convetor
    env: node
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
